export const BUGS_DETAILS_REQUEST = 'BUGS_DETAILS_REQUEST';
export const BUGS_DETAILS_SUCCESS = 'BUGS_DETAILS_SUCCESS';
export const BUGS_DETAILS_FAIL = 'BUGS_DETAILS_FAIL';

export const BUG_DETAILS_REQUEST = 'BUG_DETAILS_REQUEST';
export const BUG_DETAILS_SUCCESS = 'BUG_DETAILS_SUCCESS';
export const BUG_DETAILS_FAIL = 'BUG_DETAILS_FAIL';

export const BUG_CREATE_REQUEST = 'BUG_CREATE_REQUEST';
export const BUG_CREATE_SUCCESS = 'BUG_CREATE_SUCCESS';
export const BUG_CREATE_FAIL = 'BUG_CREATE_FAIL';
export const BUG_CREATE_RESET = 'BUG_CREATE_RESET';

export const BUG_DELETE_REQUEST = 'BUG_DELETE_REQUEST';
export const BUG_DELETE_SUCCESS = 'BUG_DELETE_SUCCESS';
export const BUG_DELETE_FAIL = 'BUG_DELETE_FAIL';
export const BUG_DELETE_RESET = 'BUG_DELETE_RESET';
