export const IMAGES_DETAILS_REQUEST = 'IMAGES_DETAILS_REQUEST';
export const IMAGES_DETAILS_SUCCESS = 'IMAGES_DETAILS_SUCCESS';
export const IMAGES_DETAILS_FAIL = 'IMAGES_DETAILS_FAIL';

export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST';
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS';
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL';

export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST';
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS';
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL';
export const IMAGE_CREATE_RESET = 'IMAGE_CREATE_RESET';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';
export const IMAGE_DELETE_RESET = 'IMAGE_DELETE_RESET';
